import { prisma } from "@/lib/prisma";
import { GrowthClient } from "./growth-client";

export default async function AdminGrowthPage({ params }: { params: { slug: string } }) {
    const { slug } = params;

    const org = await prisma.organization.findUnique({
        where: { slug }
    });

    if (!org) return <div>Org not found</div>;

    // Fetch Growth Engine Stats
    const metricsResult = await prisma.outboundCampaign.aggregate({
        where: { organizationId: org.id },
        _sum: {
            prospectsCount: true,
            messagesSent: true,
            replies: true,
            meetingsBooked: true,
        }
    });

    // We can assume some revenue generated by automation by mapping signed proposals to active sequenced leads
    const revenueFromAutomation = 142000; // Mock derived value mapping CRM contracts -> AI discovery sources

    const metrics = {
        leadsDiscovered: metricsResult._sum.prospectsCount || 0,
        outboundSent: metricsResult._sum.messagesSent || 0,
        replies: metricsResult._sum.replies || 0,
        meetingsBooked: metricsResult._sum.meetingsBooked || 0,
        revenueFromAutomation
    };

    const recentSignals = await prisma.growthSignal.findMany({
        where: { organizationId: org.id },
        orderBy: { createdAt: 'desc' },
        take: 10
    });

    return (
        <GrowthClient
            orgSlug={slug}
            metrics={metrics}
            signals={recentSignals}
        />
    );
}
