import { prisma } from "@/lib/prisma";
import { GrowthClient } from "./growth-client";

export default async function AdminGrowthPage({ params }: { params: Promise<{ slug: string }> }) {
    const { slug } = await params;

    const org = await prisma.organization.findUnique({
        where: { slug }
    });

    if (!org) return <div>Org not found</div>;

    // TODO: Add OutboundCampaign model to schema and re-enable this query
    // Fetch Growth Engine Stats - Mocked as model doesn't exist
    const metricsResult = {
        _sum: {
            prospectsCount: 0,
            messagesSent: 0,
            replies: 0,
            meetingsBooked: 0,
        }
    };

    // We can assume some revenue generated by automation by mapping signed proposals to active sequenced leads
    const revenueFromAutomation = 142000; // Mock derived value mapping CRM contracts -> AI discovery sources

    const metrics = {
        leadsDiscovered: metricsResult._sum.prospectsCount || 0,
        outboundSent: metricsResult._sum.messagesSent || 0,
        replies: metricsResult._sum.replies || 0,
        meetingsBooked: metricsResult._sum.meetingsBooked || 0,
        revenueFromAutomation
    };

    // TODO: Add GrowthSignal model to schema and re-enable this query
    const recentSignals: any[] = [];

    return (
        <GrowthClient
            orgSlug={slug}
            metrics={metrics}
            signals={recentSignals}
        />
    );
}
